### PR TITLE
Use the pre-built Docker image and cfdev

### PR DESCRIPTION
**Pull request by mogul**
* Using the Docker image means removes some steps and results in less waiting around for assets to be prebuilt, at the cost of having Docker installed; seems like a reasonable tradeoff to ensure we're always able to run a stable ready-to-go version!
* Using `cfdev` as the CF target instead of cloud.gov takes (much) longer to start up but the benefit is that you can fully examine all of the functionality in Stratos.

### CODE REVIEW

**Comment by mogul** [comment]
I'm leaving this in a draft state until I have a chance to verify that I've resolved a possible problem with running `ng serve --aot=false`.

**Comment by mogul** [comment]
The Stratos team resolved [the problem I was running into](https://cloudfoundry.slack.com/archives/C80EP4Y57/p1550733827019700)... It was [node version-specific](https://github.com/nodejs/node/issues/24097).

**Comment by rogeruiz** [comment]
Not ignoring this. But I’d like to test it before merging it in. :+1:

**Comment by ccostino** [comment]
We're closing this given the recent changes we had to make, including forking Stratos itself, and updating our deployment to Stratos version 4.4.0.

**Pull request closed without merging**
